---
development:
  cloud_name: dagjody43
  api_key: '833293939549732'
  api_secret: LKIM-r6T0B5zLmQIzUpiTO42HpE
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dagjody43
  api_key: '833293939549732'
  api_secret: LKIM-r6T0B5zLmQIzUpiTO42HpE
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dagjody43
  api_key: '833293939549732'
  api_secret: LKIM-r6T0B5zLmQIzUpiTO42HpE
  enhance_image_tag: true
  static_image_support: false
